apiVersion: v1
kind: PersistentVolumeClaim    
metadata:
  name: influxdb-ebs-claim-config
spec:
  accessModes:                 
    - ReadWriteOnce
  storageClassName: ebs-sc     
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim    
metadata:
  name: influxdb-ebs-claim-data
spec:
  accessModes:                 
    - ReadWriteOnce
  storageClassName: ebs-sc     
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim    
metadata:
  name: grafana-ebs-claim
spec:
  accessModes:                 
    - ReadWriteOnce
  storageClassName: ebs-sc     
  resources:
    requests:
      storage: 4Gi